#!/bin/sh -ex
cd ~/.home

# Platform-specific stuff
case `uname` in
  Darwin)
    platform=mac
    ;;
  FreeBSD)
    platform=bsd
    ;;
  MINGW*)
    platform=win
    ;;
esac

# .gitconfig
(
  for f in .gitconfig.base .gitconfig.$platform ~/.gitconfig.local; do
    [ ! -r "$f" ] || grep -Fv '# vim:' "$f"
  done
  grep -F '# vim:' .gitconfig.base
) > ~/.gitconfig

